name: flutter_code_test_dropdown_buttons
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
